# Write your MySQL query statement below
SELECT W.ID
FROM WEATHER W 
JOIN WEATHER V 
ON W.RECORDDATE = V.RECORDDATE + INTERVAL 1 DAY AND W.TEMPERATURE > V.TEMPERATURE;

-- SELECT TEMPERATURE, DAY(RECORDDATE) FROM WEATHER WHERE DAY(RECORDDATE) - 1 >
-- SELECT TEMPERATURE 
