# Write your MySQL query statement below
(SELECT E.NAME, B.BONUS FROM EMPLOYEE AS E LEFT JOIN BONUS AS B ON E.EMPID = B.EMPID WHERE B.BONUS IS NULL OR B.BONUS <1000 )
-- SELECT E.NAME, B.BONUS FROM EMPLOYEE AS E JOIN BONUS AS B ON E.EMPID != B.EMPID AND B.BONUS <1000