# Write your MySQL query statement below
SELECT V.CUSTOMER_ID, COUNT(*) AS COUNT_NO_TRANS
FROM VISITS V
WHERE NOT EXISTS (
    SELECT *
    FROM TRANSACTIONS T 
    WHERE V.VISIT_ID = T.VISIT_ID
)
GROUP BY V.CUSTOMER_ID;