# Write your MySQL query statement below
-- SELECT E.STUDENT_ID, STUDENT_NAME, SUBJECT_NAME, ATTENDED_EXAMS FROM STUDENTS AS S JOIN EXAMINATIONS AS E 
-- SELECT E.STUDENT_ID, E.SUBJECT_NAME, COUNT(*) FROM EXAMINATIONS AS E GROUP BY E.STUDENT_ID,E.SUBJECT_NAME;
SELECT 
    E.STUDENT_ID, 
    E.STUDENT_NAME, 
    S.SUBJECT_NAME, 
    COUNT(X.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS AS E
CROSS JOIN SUBJECTS AS S
LEFT JOIN EXAMINATIONS AS X 
    ON E.STUDENT_ID = X.STUDENT_ID 
    AND S.SUBJECT_NAME = X.SUBJECT_NAME
GROUP BY E.STUDENT_ID, E.STUDENT_NAME, S.SUBJECT_NAME
ORDER BY E.STUDENT_ID, S.SUBJECT_NAME;
