# Write your MySQL query statement below
SELECT T.REQUEST_AT AS DAY,
ROUND(SUM(CASE WHEN T.STATUS = "COMPLETED" THEN 0 ELSE 1 END) / COUNT(*),2) AS "CANCELLATION RATE"
-- SELECT SUM(CASE WHEN T.STATUS = "completed" THEN 0 ELSE 1 END)
FROM TRIPS T JOIN USERS U
ON T.CLIENT_ID = U.USERS_ID
WHERE U.BANNED = "NO" AND T.DRIVER_ID IN (SELECT T.DRIVER_ID FROM TRIPS T JOIN USERS U
ON T.DRIVER_ID = U.USERS_ID
WHERE U.BANNED = "NO")
AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY T.REQUEST_AT