# Write your MySQL query statement below
SELECT DISTINCT B.SALES_NAME AS "NAME" FROM (
SELECT S.NAME AS SALES_NAME, C.NAME AS COM_NAME FROM 
SALESPERSON S
LEFT JOIN ORDERS O
ON S.SALES_ID = O.SALES_ID
LEFT JOIN COMPANY C
ON O.COM_ID = C.COM_ID ) B
WHERE B.SALES_NAME NOT IN (
SELECT S.NAME AS SALES_NAME FROM 
SALESPERSON S
LEFT JOIN ORDERS O
ON S.SALES_ID = O.SALES_ID
LEFT JOIN COMPANY C
ON O.COM_ID = C.COM_ID 
WHERE C.NAME = "RED" 
)

-- WHERE C.NAME <> "RED" OR C.NAME IS NULL
