# Write your MySQL query statement below
SELECT Q.QUERY_NAME, 
ROUND(AVG(Q.RATING / NULLIF(Q.POSITION, 0)), 2) AS QUALITY,
ROUND(100.0 * SUM(CASE WHEN Q.RATING < 3 THEN 1 ELSE 0 END) / COUNT(Q.QUERY_NAME), 2) 
AS POOR_QUERY_PERCENTAGE
FROM QUERIES AS Q 
GROUP BY Q.QUERY_NAME;
