# Write your MySQL query statement below
-- SELECT A.MACHINE_ID,A.TIMESTAMP, B.MACHINE_ID,B.TIMESTAMP FROM ACTIVITY AS A JOIN ACTIVITY AS B ON A.MACHINE_ID = B.MACHINE_ID
WITH START_EVENTS AS (
    SELECT TIMESTAMP AS START_TIME, MACHINE_ID,
           ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY TIMESTAMP) AS rn
    FROM ACTIVITY 
    WHERE ACTIVITY_TYPE = 'START'
),
END_EVENTS AS (
    SELECT TIMESTAMP AS END_TIME, MACHINE_ID,
           ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY TIMESTAMP) AS rn
    FROM ACTIVITY 
    WHERE ACTIVITY_TYPE = 'END'
)
SELECT D.MACHINE_ID, ROUND(AVG(D.DURATION),3) AS PROCESSING_TIME FROM 
(SELECT 
    S.MACHINE_ID, 
    S.START_TIME, 
    E.END_TIME, 
    E.END_TIME - S.START_TIME AS DURATION
FROM START_EVENTS S
JOIN END_EVENTS E 
ON S.MACHINE_ID = E.MACHINE_ID AND S.rn = E.rn) 
AS D
GROUP BY MACHINE_ID;


-- SELECT TIMESTAMP FROM ACTIVITY WHERE ACTIVITY_TYPE = "END" 
-- SELECT TIMESTAMP FROM ACTIVITY WHERE ACTIVITY_TYPE = "START" 