# Write your MySQL query statement below
SELECT 
    R.CONTEST_ID, 
    ROUND((COUNT(U.USER_ID) / (SELECT COUNT(*) FROM USERS)) * 100, 2) AS PERCENTAGE
FROM REGISTER AS R
JOIN USERS AS U ON U.USER_ID = R.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, R.CONTEST_ID ASC;
