# Write your MySQL query statement below
WITH CTE AS (
    SELECT *, DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEE
)

SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM CTE E JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE E.RNK = 1

-- GROUP BY E.DEPARTMENTID
-- ORDER BY E.SALARY DESC
