# Write your MySQL query statement below
WITH CTE AS (
    SELECT *, ROW_NUMBER() OVER(PARTITION BY PLAYER_ID ORDER BY EVENT_DATE)
    AS RN
    FROM ACTIVITY
)
SELECT PLAYER_ID,
EVENT_DATE AS FIRST_LOGIN
FROM CTE
WHERE RN = 1